name: info_kit
description: Provides all basic info about your application. App flavor, Version, Device size, Flavor specific environment variables, and more.
version: 1.0.0+1
repository: https://github.com/zvikarp/info_kit

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  package_info_plus: ^1.4.3+1
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
